"""
main.py — RNA-seq simulation pipeline entry point.

What it does:
    Orchestrates the full 3-phase RNA-seq simulation pipeline:
      Phase 1 : prepare_reference.py   — GTF + genome → simulation-ready reference files
      Phase 2 : generate_abundances.py — synthetic TPM abundance profile
      Phase 3a: simulate_illumina.py   — paired-end Illumina reads via RSEM
      Phase 3b: simulate_pacbio.py     — PacBio CCS reads via IsoSeqSim
      Phase 3c: simulate_ont.py        — ONT reads via Trans-NanoSim

    All configuration is passed via CLI arguments (see run.sh).
    Default values are defined in the DEFAULTS block below.
    Outputs land in a timestamped folder: files/results/exprmnt_{timestamp}/

Inputs (pass via CLI or set defaults below):
    --genome        GRCh38 genome FASTA
    --gtf           GENCODE GTF annotation
    --rsem_model    RSEM pre-trained model file (Illumina only)
    --abundance_mode  lognormal | custom | uniform

Outputs (files/results/exprmnt_{timestamp}/):
    experiment_description.log  — full config dump + what/why/expected outcome
    running.log                 — stdout (first line: Script: <path>)
    ref_data/                   — Phase 1 reference files
    abundances.tsv              — TPM profile (ground truth expression)
    Illumina.simulated_1.fq     — Illumina paired-end reads (forward)
    Illumina.simulated_2.fq     — Illumina paired-end reads (reverse)
    PacBio.simulated.fasta      — PacBio CCS reads
    ONT.simulated.fastq         — ONT reads
    *.isoform_counts.tsv        — per-technology ground-truth read counts
    *.read_to_isoform.tsv       — read ID → isoform mapping
    results_summary.txt         — read count totals and isoform coverage stats
    runtime.txt                 — total wall-clock time
    code_snapshot/              — exact copy of code/Simulations/ at run time

Estimated runtime (full run, 16 threads):
    Phase 1 — prepare reference     : ~TBD
    Phase 2 — generate abundances   : ~TBD
    Phase 3a — Illumina (100M reads): ~TBD
    Phase 3b — PacBio  (10M reads)  : ~TBD
    Phase 3c — ONT     (30M reads)  : ~TBD
    Total                           : ~TBD

Run:
    cd /gpfs/commons/home/atalukder/RNA_Splicing
    bash code/Simulations/run.sh          # recommended — set all options in run.sh

    OR call directly (example):
    python code/Simulations/main.py \\
        --genome  data/ReqToSimulateData/human.genome.fasta \\
        --gtf     data/ReqToSimulateData/human.annotation.gtf \\
        --pacbio_count 1000 --test_mode
"""

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

# ============================================================
# DEFAULTS — fallback values when no CLI argument is provided.
# Normally you do not edit this file; set everything in run.sh.
# ============================================================

DEFAULTS = dict(
    # Input files
    genome          = "data/ReqToSimulateData/human.genome.fasta",
    gtf             = "data/ReqToSimulateData/human.annotation.gtf",
    rsem_model      = "data/ReqToSimulateData/Illumina150.RNA.model",
    sqanti_prefix   = "",
    n_novel         = 0,
    polya_len       = 100,

    # Phase toggles
    skip_phase1     = False,
    skip_phase2     = False,
    skip_illumina   = False,
    skip_pacbio     = False,
    skip_ont        = True,   # ONT off by default (needs separate env with HTSeq)

    # Abundance
    abundance_mode      = "lognormal",
    custom_tpm_file     = "",
    cancer_genes_file   = "",
    cancer_fold_change  = 5.0,
    dropout_fraction    = 0.3,
    abundance_mu        = 2.0,
    abundance_sigma     = 2.0,

    # Read counts
    illumina_count  = 100_000_000,
    pacbio_count    =  10_000_000,
    ont_count       =  30_000_000,
    ont_type        = "cDNA",

    # Run settings
    threads             = 16,
    seed                = 42,
    keep_isoform_ids    = False,
    noise_reads         = False,
    test_mode           = False,
    test_illumina_count =  10_000,
    test_pacbio_count   =   1_000,
    test_ont_count      =   1_000,
)

# ============================================================
# Do not edit below this line
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent  # RNA_Splicing/
PIPELINE_DIR = Path(__file__).resolve().parent                # code/Simulations/
SRC_DIR      = PIPELINE_DIR / "src"
sys.path.insert(0, str(SRC_DIR))

from utility import create_run_dir, save_runtime, save_code_snapshot  # noqa: E402


def parse_args() -> argparse.Namespace:
    """
    Parse CLI arguments. All arguments are optional — unset ones fall back to DEFAULTS.

    Returns:
        argparse.Namespace: Parsed arguments.
    """
    D = DEFAULTS
    p = argparse.ArgumentParser(
        description="RNA-seq simulation pipeline",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    # --- Input files ---
    g = p.add_argument_group("Input files")
    g.add_argument("--genome",        default=D["genome"],      help="GRCh38 genome FASTA")
    g.add_argument("--gtf",           default=D["gtf"],         help="GENCODE GTF annotation")
    g.add_argument("--rsem_model",    default=D["rsem_model"],  help="RSEM pre-trained model file")
    g.add_argument("--sqanti_prefix", default=D["sqanti_prefix"], help="SQANTI output prefix (optional)")
    g.add_argument("--n_novel",       default=D["n_novel"],     type=int,   help="Novel isoforms to add from SQANTI")
    g.add_argument("--polya_len",     default=D["polya_len"],   type=int,   help="Poly-A tail length (bp)")

    # --- Phase toggles ---
    g = p.add_argument_group("Phase toggles (use --skip_X to disable a phase)")
    g.add_argument("--skip_phase1",   action="store_true", default=D["skip_phase1"],  help="Skip Phase 1 (use existing ref_data/)")
    g.add_argument("--skip_phase2",   action="store_true", default=D["skip_phase2"],  help="Skip Phase 2 (use existing abundances.tsv)")
    g.add_argument("--skip_illumina", action="store_true", default=D["skip_illumina"],help="Skip Illumina simulation")
    g.add_argument("--skip_pacbio",   action="store_true", default=D["skip_pacbio"],  help="Skip PacBio simulation")
    g.add_argument("--skip_ont",      action="store_true", default=D["skip_ont"],     help="Skip ONT simulation")

    # --- Abundance ---
    g = p.add_argument_group("Abundance parameters")
    g.add_argument("--abundance_mode",     default=D["abundance_mode"],    choices=["lognormal", "custom", "uniform"], help="Abundance profile mode")
    g.add_argument("--custom_tpm_file",    default=D["custom_tpm_file"],   help="TSV (transcript_id, TPM) for mode=custom")
    g.add_argument("--cancer_genes_file",  default=D["cancer_genes_file"], help="Gene list to up-regulate (mode=custom)")
    g.add_argument("--cancer_fold_change", default=D["cancer_fold_change"],type=float, help="Fold-change for cancer genes")
    g.add_argument("--dropout_fraction",   default=D["dropout_fraction"],  type=float, help="Fraction of transcripts with TPM=0 (lognormal)")
    g.add_argument("--abundance_mu",       default=D["abundance_mu"],      type=float, help="Log-normal mean (lognormal)")
    g.add_argument("--abundance_sigma",    default=D["abundance_sigma"],   type=float, help="Log-normal sigma (lognormal)")

    # --- Read counts ---
    g = p.add_argument_group("Read counts")
    g.add_argument("--illumina_count", default=D["illumina_count"], type=int, help="Illumina read pairs to simulate")
    g.add_argument("--pacbio_count",   default=D["pacbio_count"],   type=int, help="PacBio reads to simulate")
    g.add_argument("--ont_count",      default=D["ont_count"],      type=int, help="ONT reads to simulate")
    g.add_argument("--ont_type",       default=D["ont_type"],       choices=["cDNA", "dRNA"], help="ONT chemistry")

    # --- Run settings ---
    g = p.add_argument_group("Run settings")
    g.add_argument("--threads",             default=D["threads"],  type=int, help="CPU threads")
    g.add_argument("--seed",                default=D["seed"],     type=int, help="Random seed")
    g.add_argument("--keep_isoform_ids",    action="store_true",   default=D["keep_isoform_ids"], help="Preserve isoform IDs in PacBio read names")
    g.add_argument("--noise_reads",         action="store_true",   default=D["noise_reads"],      help="Include noise reads in ONT output")
    g.add_argument("--test_mode",           action="store_true",   default=D["test_mode"],        help="Override counts with tiny values for a quick test")
    g.add_argument("--test_illumina_count", default=D["test_illumina_count"], type=int, help="Illumina count in test mode")
    g.add_argument("--test_pacbio_count",   default=D["test_pacbio_count"],   type=int, help="PacBio count in test mode")
    g.add_argument("--test_ont_count",      default=D["test_ont_count"],      type=int, help="ONT count in test mode")

    return p.parse_args()


def _run(cmd: list, log_fh=None) -> None:
    """
    Run a subprocess command, streaming output to stdout and optionally to a log file.

    Args:
        cmd    (list): Command and arguments to execute.
        log_fh       : Open file handle to write output to (optional).

    Returns:
        None

    Raises:
        SystemExit: If the subprocess returns a non-zero exit code.
    """
    print(f"\n[main] Running: {' '.join(str(c) for c in cmd)}\n")
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    for line in proc.stdout:
        print(line, end="")
        if log_fh:
            log_fh.write(line)
    proc.wait()
    if proc.returncode != 0:
        print(f"[main] ERROR: command failed (exit {proc.returncode})")
        sys.exit(proc.returncode)


def write_experiment_description(run_dir: Path, config: dict) -> None:
    """
    Write experiment_description.log with the full config and expected outcomes.

    Args:
        run_dir (Path): Timestamped results folder.
        config  (dict): All resolved config values.

    Returns:
        None
    """
    lines = [
        "=" * 70,
        "RNA-seq Simulation Pipeline — Experiment Description",
        "=" * 70,
        "",
        "Goal:",
        "  Generate synthetic RNA-seq reads for Illumina, PacBio, and ONT",
        "  with known ground-truth isoform abundances for benchmarking",
        "  isoform quantification tools.",
        "",
        "Expected outputs:",
        "  - Simulated reads per technology (FASTQ / FASTA)",
        "  - Per-isoform ground-truth read counts",
        "  - Read-to-isoform mapping tables",
        "",
        "Full config:",
        json.dumps(config, indent=2),
        "",
    ]
    out = run_dir / "experiment_description.log"
    out.write_text("\n".join(lines))
    print(f"[main] Wrote experiment_description.log → {out}")


def write_results_summary(run_dir: Path) -> None:
    """
    Scan the run directory for output files and write results_summary.txt.

    Args:
        run_dir (Path): Timestamped results folder.

    Returns:
        None
    """
    lines = ["RNA-seq Simulation — Results Summary", "=" * 50, ""]
    checks = [
        ("Illumina.simulated_1.fq",     "Illumina reads (R1)"),
        ("Illumina.simulated_2.fq",     "Illumina reads (R2)"),
        ("PacBio.simulated.fasta",      "PacBio reads"),
        ("ONT.simulated.fastq",         "ONT reads"),
        ("Illumina.isoform_counts.tsv", "Illumina isoform counts"),
        ("PacBio.isoform_counts.tsv",   "PacBio isoform counts"),
        ("ONT.isoform_counts.tsv",      "ONT isoform counts"),
    ]
    for fname, label in checks:
        p = run_dir / fname
        if p.exists():
            size_mb = p.stat().st_size / 1e6
            lines.append(f"  [OK]   {label:35s}  {size_mb:.1f} MB")
        else:
            lines.append(f"  [SKIP] {label:35s}  (not generated)")

    out = run_dir / "results_summary.txt"
    out.write_text("\n".join(lines) + "\n")
    print(f"[main] Wrote results_summary.txt → {out}")


def main() -> None:
    """
    Main orchestrator: runs Phase 1 → Phase 2 → Phase 3 (Illumina / PacBio / ONT).

    Reads all parameters from CLI arguments (see parse_args).
    Each phase is called as a subprocess so phases can be re-run independently.

    Args:
        None

    Returns:
        None
    """
    args      = parse_args()
    run_start = time.time()
    python    = sys.executable

    # Apply test-mode count overrides
    eff_illumina = args.test_illumina_count if args.test_mode else args.illumina_count
    eff_pacbio   = args.test_pacbio_count   if args.test_mode else args.pacbio_count
    eff_ont      = args.test_ont_count      if args.test_mode else args.ont_count

    config = vars(args) | dict(
        eff_illumina_count=eff_illumina,
        eff_pacbio_count=eff_pacbio,
        eff_ont_count=eff_ont,
    )

    # Create timestamped output directory
    run_dir    = create_run_dir(str(PROJECT_ROOT / "files" / "results"))
    ref_dir    = run_dir / "ref_data"
    ref_prefix = str(ref_dir / "human_sim")
    ref_dir.mkdir(parents=True, exist_ok=True)

    # Open running.log — first line must be: Script: <path>
    log_path = run_dir / "running.log"
    log_fh   = open(log_path, "w")
    log_fh.write(f"Script: {__file__}\n")

    write_experiment_description(run_dir, config)

    print("=" * 70)
    print("  RNA-seq Simulation Pipeline")
    print(f"  Run dir   : {run_dir}")
    print(f"  Test mode : {args.test_mode}")
    print(f"  Phases    : phase1={not args.skip_phase1}  phase2={not args.skip_phase2}")
    print(f"  Techs     : illumina={not args.skip_illumina}  pacbio={not args.skip_pacbio}  ont={not args.skip_ont}")
    print(f"  Counts    : illumina={eff_illumina:,}  pacbio={eff_pacbio:,}  ont={eff_ont:,}")
    print("=" * 70)

    # ── Phase 1: Prepare Reference ────────────────────────────────────────────
    if not args.skip_phase1:
        print("\n[main] ── Phase 1: Prepare Reference ──")
        cmd = [
            python, str(SRC_DIR / "prepare_reference.py"),
            "--genome",    args.genome,
            "--gtf",       args.gtf,
            "--output",    ref_prefix,
            "--polya_len", str(args.polya_len),
        ]
        if args.sqanti_prefix:
            cmd += ["--sqanti", args.sqanti_prefix, "--n_novel", str(args.n_novel)]
        _run(cmd, log_fh)
    else:
        print("[main] Phase 1 skipped — using existing ref_data/")
        log_fh.write("[main] Phase 1 skipped\n")

    # ── Phase 2: Generate Abundances ──────────────────────────────────────────
    abundances_tsv = str(run_dir / "abundances.tsv")

    if not args.skip_phase2:
        print("\n[main] ── Phase 2: Generate Abundances ──")
        cmd = [
            python, str(SRC_DIR / "generate_abundances.py"),
            "--mode",        args.abundance_mode,
            "--transcripts", f"{ref_prefix}.transcripts.fasta",
            "--output",      abundances_tsv,
            "--seed",        str(args.seed),
            "--dropout",     str(args.dropout_fraction),
            "--mu",          str(args.abundance_mu),
            "--sigma",       str(args.abundance_sigma),
        ]
        if args.abundance_mode == "custom":
            cmd += ["--custom_tpm", args.custom_tpm_file]
            if args.cancer_genes_file:
                cmd += ["--cancer_genes", args.cancer_genes_file,
                        "--fold_change",  str(args.cancer_fold_change)]
        _run(cmd, log_fh)
    else:
        print("[main] Phase 2 skipped")
        log_fh.write("[main] Phase 2 skipped\n")

    # ── Phase 3a: Illumina ────────────────────────────────────────────────────
    if not args.skip_illumina:
        print("\n[main] ── Phase 3a: Illumina (RSEM) ──")
        _run([
            python, str(SRC_DIR / "simulate_illumina.py"),
            "--reference_prefix", ref_prefix,
            "--abundances",       abundances_tsv,
            "--output_dir",       str(run_dir),
            "--model_file",       args.rsem_model,
            "--threads",          str(args.threads),
            "--read_count",       str(eff_illumina),
            "--seed",             str(args.seed),
        ], log_fh)

    # ── Phase 3b: PacBio ──────────────────────────────────────────────────────
    if not args.skip_pacbio:
        print("\n[main] ── Phase 3b: PacBio (IsoSeqSim) ──")
        cmd = [
            python, str(SRC_DIR / "simulate_pacbio.py"),
            "--reference_prefix", ref_prefix,
            "--genome",           args.genome,
            "--abundances",       abundances_tsv,
            "--output_dir",       str(run_dir),
            "--threads",          str(args.threads),
            "--read_count",       str(eff_pacbio),
            "--seed",             str(args.seed),
        ]
        if args.keep_isoform_ids:
            cmd.append("--keep_isoform_ids")
        _run(cmd, log_fh)

    # ── Phase 3c: ONT ─────────────────────────────────────────────────────────
    if not args.skip_ont:
        print("\n[main] ── Phase 3c: ONT (Trans-NanoSim) ──")
        cmd = [
            python, str(SRC_DIR / "simulate_ont.py"),
            "--reference_prefix", ref_prefix,
            "--abundances",       abundances_tsv,
            "--output_dir",       str(run_dir),
            "--ont_type",         args.ont_type,
            "--threads",          str(args.threads),
            "--read_count",       str(eff_ont),
            "--seed",             str(args.seed),
        ]
        if args.noise_reads:
            cmd.append("--noise_reads")
        _run(cmd, log_fh)

    # ── Wrap up ───────────────────────────────────────────────────────────────
    write_results_summary(run_dir)
    save_code_snapshot(run_dir, PIPELINE_DIR)
    save_runtime(run_dir, time.time() - run_start)

    log_fh.close()
    print("\n" + "=" * 70)
    print(f"[main] Pipeline complete. Results: {run_dir}")
    print("=" * 70)


if __name__ == "__main__":
    main()
